//ACTIVITY_SERVICE
//ALARM_SERVICE
//AUDIO_SERVICE
//CLIPBOARD_SERVICE
//KEYGUARD_SERVICE
//LAYOUT_INFLATER_SERVICE
//LOCATION_SERVICE
//NOTIFICATION_SERVICE
//
//
//


WifiManager wifiManager = (WifiManager) getSystemService(WIFI_SERVICE);


