//ACTIVITY_SERVICE
//ALARM_SERVICE
//AUDIO_SERVICE
//CLIPBOARD_SERVICE
//KEYGUARD_SERVICE
//LAYOUT_INFLATER_SERVICE
//LOCATION_SERVICE
//NOTIFICATION_SERVICE
//POWER_SERVICE
//SEARCH_SERVICE
//SENSOR_SERVICE
//TELEPHONY_SERVICE
//VIBRATOR_SERVICE
//WALLPAPER_SERVICE
//WIFI_SERVICE
//WINDOW_SERVICE
//INPUT_METHOD_SERVICE
//ACCESSIBILITY_SERVICE
//ACCOUNT_SERVICE
//DEVICE_POLICY_SERVICE
//DROPBOX_SERVICE
//UI_MODE_SERVICE
//DOWNLOAD_SERVICE
//NFC_SERVICE
//USB_SERVICE
//TEXT_SERVICES_MANAGER_SERVICE
//WIFI_P2P_SERVICE
//INPUT_SERVICE
//MEDIA_ROUTER_SERVICE
//NSD_SERVICE
//DISPLAY_SERVICE
//USER_SERVICE


WifiManager wifiManager = (WifiManager) getSystemService(WIFI_SERVICE);


